version: "3"

services:
  api:
    build: .
    environment:
      ASPNETCORE_ENVIRONMENT: docker
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mongo:4.0-xenial
    restart: always
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
volumes:
  db-data: